### ISSUE TITLE
CasperCG Media Scanner status is bad, can`t get it work

### ISSUE THREAD

**Issue by Ronvaknins** [baltedewit/folderplayout#6]
![image](https://user-images.githubusercontent.com/48179479/88261582-44a23880-cccf-11ea-9e79-3bc21767a855.png)

hi i`v been trying to load folder, but it dosen't seems to load it to the playlist, i tried Server 2.2 , and server 2.0.7 . the media scanner is always bad, is there any way to fix that?
this is my config file , also tried entering 127.0.0.1 instead of "localhost"

![image](https://user-images.githubusercontent.com/48179479/88261893-ceea9c80-cccf-11ea-8b19-11873f734452.png)

am i missing somthing?

Thanks!

**Comment by mint-dewit** [comment]
You need to use this fork of mediascanner: https://github.com/nrkno/tv-automation-media-scanner

It would also be best to user Server 2.1.11 NRK: https://github.com/nrkno/tv-automation-casparcg-server/

**Comment by Ronvaknins** [comment]
> You need to use this fork of mediascanner: https://github.com/nrkno/tv-automation-media-scanner
> 
> It would also be best to user Server 2.1.11 NRK: https://github.com/nrkno/tv-automation-casparcg-server/

hi thanks!!, i`v added folder to the schedule but it seems like it`s isn't added to the playlist, is there any video or anything on how to run it? 
![image](https://user-images.githubusercontent.com/48179479/88269753-4a067f80-ccdd-11ea-93f8-5c22c3858759.png)
when i save it the date and time resets, did i input the time value right?

**Comment by mint-dewit** [comment]
You can't use absolute paths, only paths relative to the media folder as used by CasparCG will work.

You have to click "add daterange" and "add time" before they are actually added to the entry. Then you click the save icon in the right top to actually save the schedule for playout.

_Ps: you only have to select the days if you want it to not play every day_

**Comment by Ronvaknins** [comment]
> You can't use absolute paths, only paths relative to the media folder as used by CasparCG will work.
> 
> You have to click "add daterange" and "add time" before they are actually added to the entry. Then you click the save icon in the right top to actually save the schedule for playout.
> 
> _Ps: you only have to select the days if you want it to not play every day_

thanks i`v i understand the time is hh:mm:ss formated
and about the path you mean the CasperCG media folder in the server?
the input should be like this?
"media/"

or 

the server full path on the windows?
"C:\CasperCG\casparcg-server-2.2.0-stable-windows\media"

or 
http://127.0.0.1:8000/media

sorry for all the questions i'm new to casperCG still learning how it works (also fresh computer science student)

can you send me a picture of a settings example for the scheduler? 

thanks!

**Comment by mint-dewit** [comment]
![afbeelding](https://user-images.githubusercontent.com/9898648/88275922-77076200-ccde-11ea-9553-084f35d2e856.png)

In the screenshot you see I have a schedule entry for a folder called `clips`, in Explorer I have my CasparCG media folder opened and as you can see there is a folder called `clips`. That's  the folder it will play. In my case the media folder is "Documents/CasparCG/media" but as you can see I do not include this in the folderplayout schedule.
